"""
Markdown 格式化器
"""
import os
from datetime import datetime

from datasources.base import ContentItem


class MarkdownFormatter:
    """Markdown 格式化器"""

    def __init__(self, output_dir: str = "output"):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def format_item(self, item: ContentItem, include_author: bool = True) -> str:
        """格式化单条内容"""
        lines = []

        if include_author:
            lines.append(f"**[@{item.author_username}](https://x.com/{item.author_username})** ({item.author_name})")

        lines.append(item.content)

        # 元信息
        meta = []
        meta.append(f"🕐 {item.created_at.strftime('%H:%M')}")
        if item.likes:
            meta.append(f"❤️ {item.likes}")
        if item.retweets:
            meta.append(f"🔄 {item.retweets}")
        meta.append(f"[🔗 查看原文]({item.url})")

        lines.append(f"\n{' | '.join(meta)}")

        return "\n".join(lines)

    def format_category(self, category: str, items: list[ContentItem]) -> str:
        """格式化分类"""
        lines = [f"## {category}\n"]

        for i, item in enumerate(items, 1):
            lines.append(f"### {i}. {item.author_name}")
            lines.append(self.format_item(item, include_author=False))
            lines.append("")

        return "\n".join(lines)

    def format_daily_summary(
        self,
        categories: dict[str, list[ContentItem]],
        date: str | None = None
    ) -> str:
        """格式化每日摘要"""
        if date is None:
            date = datetime.now().strftime("%Y-%m-%d")

        total = sum(len(items) for items in categories.values())

        lines = [
            f"# 🤖 AI 资讯摘要 - {date}",
            "",
            f"> 共收集 **{total}** 条相关资讯，分为 **{len(categories)}** 个类别",
            "",
            "---",
            "",
        ]

        # 目录
        if categories:
            lines.append("## 📑 目录")
            lines.append("")
            for category in categories.keys():
                lines.append(f"- [{category}](#{self._slugify(category)})")
            lines.append("")
            lines.append("---")
            lines.append("")

        # 内容
        for category, items in categories.items():
            lines.append(self.format_category(category, items))
            lines.append("")

        # 页脚
        lines.extend([
            "---",
            "",
            f"*Generated by AI News Agent on {datetime.now().strftime('%Y-%m-%d %H:%M')}* 🦞",
            "",
        ])

        return "\n".join(lines)

    def save_daily_summary(
        self,
        categories: dict[str, list[ContentItem]],
        date: str | None = None,
        filename: str | None = None
    ) -> str:
        """保存每日摘要"""
        if date is None:
            date = datetime.now().strftime("%Y-%m-%d")

        if filename is None:
            filename = f"{date}.md"

        filepath = os.path.join(self.output_dir, filename)
        content = self.format_daily_summary(categories, date)

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)

        print(f"Saved: {filepath}")
        return filepath

    def _slugify(self, text: str) -> str:
        """转换为 URL slug"""
        return text.lower().replace(" ", "-").replace("/", "-")
