"""
输出格式化
生成 Markdown 格式的每日 AI 资讯摘要
"""
import os
from datetime import datetime, timedelta
from typing import List, Dict, Any, Optional
from urllib.parse import quote


class MarkdownFormatter:
    """Markdown 格式化器"""
    
    def __init__(self, output_dir: str = "output"):
        """
        初始化格式化器
        
        Args:
            output_dir: 输出目录
        """
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)
    
    def format_tweet(self, tweet: Dict[str, Any], include_author: bool = True) -> str:
        """
        格式化单条推文为 Markdown
        
        Args:
            tweet: 推文数据
            include_author: 是否包含作者信息
            
        Returns:
            Markdown 文本
        """
        text = tweet.get("text", "")
        tweet_id = tweet.get("id", "")
        author_username = tweet.get("author_username", "unknown")
        author_name = tweet.get("author_name", author_username)
        created_at = tweet.get("created_at", "")
        
        # 格式化时间
        if created_at:
            try:
                dt = datetime.fromisoformat(created_at.replace("Z", "+00:00"))
                time_str = dt.strftime("%H:%M")
            except:
                time_str = created_at[:10]
        else:
            time_str = ""
        
        # 构建推文链接
        tweet_url = f"https://x.com/{author_username}/status/{tweet_id}"
        
        # 格式化互动数
        metrics = tweet.get("public_metrics", {})
        likes = metrics.get("like_count", 0)
        retweets = metrics.get("retweet_count", 0)
        
        lines = []
        
        # 作者信息
        if include_author:
            lines.append(f"**[@{author_username}](https://x.com/{author_username})** ({author_name})")
        
        # 推文内容
        lines.append(f"{text}")
        
        # 元信息
        meta = []
        if time_str:
            meta.append(f"🕐 {time_str}")
        if likes:
            meta.append(f"❤️ {likes}")
        if retweets:
            meta.append(f"🔄 {retweets}")
        meta.append(f"[🔗 查看原文]({tweet_url})")
        
        lines.append(f"\n{' | '.join(meta)}")
        
        return "\n".join(lines)
    
    def format_category(
        self, 
        category: str, 
        tweets: List[Dict[str, Any]]
    ) -> str:
        """
        格式化分类区块
        
        Args:
            category: 分类名称
            tweets: 推文列表
            
        Returns:
            Markdown 文本
        """
        lines = [f"## {category}\n"]
        
        for i, tweet in enumerate(tweets, 1):
            lines.append(f"### {i}. {tweet.get('author_name', 'Unknown')}")
            lines.append(self.format_tweet(tweet, include_author=False))
            lines.append("")  # 空行
        
        return "\n".join(lines)
    
    def format_daily_summary(
        self,
        categorized_tweets: Dict[str, List[Dict[str, Any]]],
        date: Optional[str] = None,
        summary_data: Optional[Dict[str, Any]] = None
    ) -> str:
        """
        格式化每日摘要
        
        Args:
            categorized_tweets: 分类后的推文
            date: 日期字符串，默认为今天
            summary_data: 摘要数据
            
        Returns:
            Markdown 文本
        """
        if date is None:
            date = datetime.now().strftime("%Y-%m-%d")
        
        # 计算统计数据
        total_tweets = sum(len(tweets) for tweets in categorized_tweets.values())
        total_categories = len(categorized_tweets)
        
        lines = [
            f"# 🤖 AI 资讯摘要 - {date}",
            "",
            f"> 共收集 **{total_tweets}** 条相关推文，分为 **{total_categories}** 个类别",
            "",
            "---",
            "",
        ]
        
        # 目录
        if categorized_tweets:
            lines.append("## 📑 目录")
            lines.append("")
            for category in categorized_tweets.keys():
                lines.append(f"- [{category}](#{self._slugify(category)})")
            lines.append("")
            lines.append("---")
            lines.append("")
        
        # 各分类内容
        for category, tweets in categorized_tweets.items():
            lines.append(self.format_category(category, tweets))
            lines.append("")
        
        # 页脚
        lines.extend([
            "---",
            "",
            f"*Generated by AI News Agent on {datetime.now().strftime('%Y-%m-%d %H:%M')}* 🦞",
            "",
        ])
        
        return "\n".join(lines)
    
    def save_daily_summary(
        self,
        categorized_tweets: Dict[str, List[Dict[str, Any]]],
        date: Optional[str] = None,
        filename: Optional[str] = None
    ) -> str:
        """
        保存每日摘要到文件
        
        Args:
            categorized_tweets: 分类后的推文
            date: 日期字符串
            filename: 文件名，默认为 YYYY-MM-DD.md
            
        Returns:
            保存的文件路径
        """
        if date is None:
            date = datetime.now().strftime("%Y-%m-%d")
        
        if filename is None:
            filename = f"{date}.md"
        
        filepath = os.path.join(self.output_dir, filename)
        
        content = self.format_daily_summary(categorized_tweets, date)
        
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        
        print(f"Saved daily summary to: {filepath}")
        return filepath
    
    def _slugify(self, text: str) -> str:
        """
        将文本转换为 URL slug
        
        Args:
            text: 原始文本
            
        Returns:
            slug
        """
        return text.lower().replace(" ", "-").replace("/", "-")
    
    def format_simple_list(
        self,
        tweets: List[Dict[str, Any]],
        title: str = "AI News"
    ) -> str:
        """
        格式化为简单列表（用于快速预览）
        
        Args:
            tweets: 推文列表
            title: 标题
            
        Returns:
            Markdown 文本
        """
        lines = [f"# {title}\n"]
        
        for tweet in tweets:
            author = tweet.get("author_username", "unknown")
            text = tweet.get("text", "")[:100]
            if len(tweet.get("text", "")) > 100:
                text += "..."
            
            lines.append(f"- **@{author}**: {text}")
        
        return "\n".join(lines)
    
    def save_simple_list(
        self,
        tweets: List[Dict[str, Any]],
        filename: str = "quick_view.md"
    ) -> str:
        """
        保存简单列表
        
        Args:
            tweets: 推文列表
            filename: 文件名
            
        Returns:
            保存的文件路径
        """
        filepath = os.path.join(self.output_dir, filename)
        
        content = self.format_simple_list(tweets)
        
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        
        print(f"Saved quick view to: {filepath}")
        return filepath
